### ISSUE TITLE
add durations to data section

### ISSUE THREAD

**Issue by freeman-lab** [CodeNeuro/neurofinder#20]
We should add something about the data durations and frame rates to the "download data" section of the main page, to make it a little easier to find at a glance.

**Comment by marius10p** [comment]
How about adding that information when you mouse over the scores for each dataset on the website? 

On the previous  version of the website, I could see at a glance the mean image for each recording when I would mouse over the scores.  I really liked that, it gave me an immediate impression of what kind of data each benchmark is assessing.

**Comment by freeman-lab** [comment]
Added extra information to the mouse over. It now shows the area, duration, rate, and lab. Closing this issue, the mean image will be added in a separate update.
