### ISSUE TITLE
scale detection distance threshold by pixels?

### ISSUE THREAD

**Issue by marius10p** [CodeNeuro/neurofinder#21]
Most datasets are around ~1pix per micron, but the Losonczy lab ones are ~2pix per micron.

**Comment by freeman-lab** [comment]
Thanks for flagging this, will add a correction in the submission evaluation code.

**Comment by freeman-lab** [comment]
With commit https://github.com/codeneuro/neurofinder/commit/400f4b53f77dc67e82a5640e053b0d04ddaa794e, evaluation scripts are now all run at a threshold of `5 microns`, which is translated to pixels given the metadata. All scores have been updated. Main effect was to increase the threshold for the Losonczy lab data, as you've pointed out. Thanks again for flagging this @marius10p !

**Comment by marius10p** [comment]
Could this change be implemented in the python comparison code as well please? I am talking about this command: neurofinder evaluate regions.json results.json

**Comment by freeman-lab** [comment]
moving discussion to https://github.com/codeneuro/neurofinder-python/issues/2
